### ISSUE TITLE
confusion about input for dataset

### ISSUE THREAD

**Issue by romainVala** [fepegar/torchio#116]
Hello

Sorry if this is obvious but I get confuse with the dataset input

Previously I was just using list of images, 
 ```
 suj = [[ Image('T1', 'path/T1', INTENSITY), 
             Image('mask', 'path/label', LABEL), ]]
```
and then
`dataset = ImagesDataset(suj)`

After a recent update I get know an error 
  TypeError: Subjects list must contain instances of torchio.Subject, not "<class 'list'>"

so I now need a subject and thought I could do :
`suj  =  [ Subject(ss) for ss in suj ]
`
but Subject does not accept a list of image : why that ?

this make the code, quite verbose, The only way is to do (as found in example_motion)
 ```
suj = [ Subject( Image('T1', 'path/T1', INTENSITY), 
                           Image('mask', 'path/label', LABEL)), ]

```
it is less convenient than a list of image ...
may be I miss the point ... ?

**Comment by romainVala** [comment]
it may be not a big deal, I found out the way to addapt : 
`suj = [ Subject(*ss) for ss in suj ] 
`
I find it easier with a list, but I am not a python expert ...

**Comment by fepegar** [comment]
I once changed the code to accept only `*images` and not `images`, but it was still working with lists of images. I [recently](https://github.com/fepegar/torchio/commit/d35d5c51cfb31ccd9c6f5c9b468f3ab590ae1bcf) modified it so that only one option is allowed.

I thought creating a list every time you want to create a new subject would be even more verbose, so implemented it like this, although I don't have strong arguments to support my decision. Using `Subject(*ss)` should indeed work for you.

**Comment by romainVala** [comment]
ok fine
