### ISSUE TITLE
Error in weighted sampler if no sampling map is passed

### ISSUE THREAD

**Issue by fepegar** [fepegar/torchio#277]
**🐛Bug**

The sampling map name should be mandatory.

**Comment by dvolgyes** [comment]
I would consider using keyword-only arguments through the project.
Namely, instead of:
def f(a,b,c=5):
you can use:
def f(a,b,*,c=5)

The difference is the calling. f(1,2,3) is valid for the first, but not for the second. f(1,2,c=3) is valid for both.
Keyword-only arguments help to stabilize API, because if you rearrange the keywords,
the function will work as it did before. 
E.g. changing from def f(a,b,*,c=5) to def f(a,b,*,d=1, c=5) is safe,
but from  def f(a,b,c=5)   to   def f(a,b,d=1,c=5) makes silently leads to mistakes when you call it as f(1,2,3).

Also, while mypy is nice for testing, pycontracts could be considered for runtime checks.
It supports well beyond basic type checking, e.g. it allows ranges:  x=int, >3, <5
This could be handy for checking dimensions, requiring valid file names, etc.

So in the above example, you could set probability map to be torch.Tensor or numpy array,
and it would give runtime error if the input was None, or none of the two types.

**Comment by fepegar** [comment]
I like the idea of using `*` in signatures: https://github.com/fepegar/torchio/pull/290#discussion_r489784437.

> E.g. changing from def f(a,b,,c=5) to def f(a,b,,d=1, c=5) is safe,
but from def f(a,b,c=5) to def f(a,b,d=1,c=5) makes silently leads to mistakes when you call it as f(1,2,3).

I guess the stars are missing in this examples.

> Also, while mypy is nice for testing, pycontracts could be considered for runtime checks.
It supports well beyond basic type checking, e.g. it allows ranges: x=int, >3, <5
This could be handy for checking dimensions, requiring valid file names, etc.

I didn't know `pycontracts`. I'll give it a try!

Thanks, @dvolgyes.

**Comment by fepegar** [comment]
I'm tinkering with `pycontracts`. It looks nice, but there are (for now) some things I don't like from the point of view of users:

1. I have to explicitly say that a number can be int or float, not just float
2. Exception messages are huge. This is something I really want to avoid
3. Docs look less nice. Examples:

<img width="675" alt="Screen Shot 2020-09-22 at 17 16 16" src="https://user-images.githubusercontent.com/12688084/93909538-c0ccf280-fcf7-11ea-9783-ec231bf3d477.png">
In this example, the user seems to be expected to understand contracts syntax.

<img width="523" alt="Screen Shot 2020-09-22 at 17 15 45" src="https://user-images.githubusercontent.com/12688084/93909542-c1fe1f80-fcf7-11ea-9eb9-c42836b6d283.png">
In this example, I have defined the `'probability'` contract before, but this is not expanded and therefore not useful for the user.

What do you think?

**Comment by fepegar** [comment]
Example of code that generates a huge error:

```python
from contracts import contract

class A:
    @contract
    def __init__(self, d: 'float'):
        pass

A(1)
```

**Comment by dvolgyes** [comment]
There is a solution for everything. 
Of course, you could educate the users/developers, but also, it is quite easy to customize the exception.
I guess this code shows everything which is needed.
If you don't like the pycontracts style, you could put your own ```contract``` (see below) into ```torchio.contract```,
and use it as:
```
from torchio import contract
@contract
....
```

And my long example with some details:
```
#!/usr/bin/python3
from contracts import contract as original_contract
from contracts.interface import ContractNotRespected

import traceback
import sys

def contract(func,*args, **kwargs):
    def wrapper(*args,**kwargs):
        try:
            result = original_contract(func)
            return result(*args,**kwargs)
        except Exception as e:
            print('You have useful information in the exception')
            for key in dir(e):
                if not key.startswith('__'):
                    print(f" e.{key} = {getattr(e,key)}")
            print(f"{e.__doc__=}")
            print(f"{func.__doc__=}")
            print("")
            print("")
            print("")
            print('Oh-oh, you made a serious error here:')
            traceback.print_stack(file=sys.stdout, limit=-1) #Let's print the stack trace without boilerplate
            print("")
            print(e.error)
            print(f"Well, the annotations for function are:")
            print(f"   {func.__annotations__}")
            print(f"")
            print(f"Maybe you should read the documentation?")
            print(f"https://torchio.readthedocs.io/search.html?q={func.__qualname__}")
            sys.exit(1)
    return wrapper

@contract
def test(x:int, z:int=3):
    """docstring comes here"""
    return x

test(1,4)
test('random input')
```

The result will be something like this (assuming it is in the test.py):
```
You have useful information in the exception
 e.args = (CheckType(int), "Expected type 'int', got <class 'str'>.", 'random input', {})
 e.context = {}
 e.contract = int
 e.error = Breach for argument 'x' to test().
Expected type 'int', got <class 'str'>.
 e.stack = [(CheckType(int), {}, 'random input')]
 e.value = random input
 e.with_traceback = <built-in method with_traceback of ContractNotRespected object at 0x7f26f496e700>
e.__doc__=' Exception thrown when a value does not respect a contract. '
func.__doc__='docstring comes here'



Oh-oh, you made a serious error here:
  File "test.py", line 41, in <module>
    test('random input')

Breach for argument 'x' to test().
Expected type 'int', got <class 'str'>.
Well, the annotations for function are:
   {'x': <class 'int'>, 'z': <class 'int'>}

Maybe you should read the documentation?
https://torchio.readthedocs.io/search.html?q=test
```

**Comment by dvolgyes** [comment]
You can also put the contracts into two places: into the contract decorator or into the docstring. 
Is it nice or not? Well, that is a good question. You can always add an extra part in the docstring, 
like a textual marker, e.g. 'Expected constraints:', and just like i printed the url,
you could cut out this part of the docstring, and print it to screen.
Then ensuring this part will be necessary during pull requests.
Or just saying, e.g. "read the documentation, variable 'x' did not fulfill the requirements
either for its type or for its value".

**Comment by dvolgyes** [comment]
You can also formulate the contracts and check them individually, like an assert at the beginning of the 
function, and make an error message if the contract is breached. 
(see ```contracts.check``` and ```contracts.check_multiple```)
These also could be wrapped / or put into a try/except section, like:
```
def custom_check(contract, variable):
   try:
      check(contract, variable)
   except:
     printf("Hey, this contract wasn't met: {contract}")
     raise Exception from None
```
Or something like this, see  the other example above too.

**Comment by fepegar** [comment]
Nice, sounds like the exceptions could be improved then. Do you have a solution for point 3. in https://github.com/fepegar/torchio/issues/277#issuecomment-696829428?

**Comment by dvolgyes** [comment]
Well, it depends how you define readability.
There are 3 ways to define contracts:
- signature
- docstring
- decorator
I hate the signature part, it looks super-confusing i think.
Docstring looks reasonably good, but might confuse single readers, so i usually end up with the decorator, like:

```
@contract(n='int, >=1')
def factorial(n):
     if n==1: return 1
    return n*factorial(n-1)
```

Since i don't use mypy, i actually don't need annotation, but it is nice to have.
As far as i remember pycontracts support multiple contracts, so you can have contract
in form of annotation and also as a decorator, but the interplay is a bit fishy, e.g. consider this:

```
@contract(n='float, >1 | int, >=1')
def factorial(n:int):
     if n==1: return 1
    return n*factorial(n-1)
```
How suppose this to work?
As long as the annotation is only defined on one place, it could not really get unsynchronized.
If it is defined at two places, it could.

But there is a soft remedy: first, you don't have to apply it everywhere. 
Use it where it is straightforward, or where it is a frequently used public interface.
Hopefully, the internal parts should be tested with unit-tests anyway, the major public interfaces
the ones what people most likely will misuse, e.g. ```__init__```.
Secondly, it can be gradually introduced after a bug fix / refactoring, checking if it helps or not.

Anyway, i am not strongly pushing it, but it helps time to time, especially with some trickier parts, e.g.
```
from pathlib import Path
new_contract('existing_file', lambda p: Path(p).exists())
new_contract('existing_dir', lambda p: Path(p).exists() and Path(p).is_dir())
```
Because for most routines, you expect a filename, but you don't actually test if it exists, etc.,
rather the ```open``` function will raise an exception. This is fine most of the time, except when the
exception is really deep in a stack trace, and it is hard to figure out what was the reason.
But stating that the file does'nt exist is a nice and straightforward explanation.

Also, 'existing_file' as a type doesn't tell much in a docstring or in a type annotation, so 
i prefer it in the decorator format.
(You could have fancy conditions, like a tensor with finite values (no NaN of inf), but these might be expensive
checks, don't overuse it. But i have used these kind of checks for debugging, they are most helpful there.
I actually wish a multi-level contract system, like some contracts could be only checked in debug mode,
some should be checked always. But the framework doesn't have such option currently.)

So my two cents:
- contracts in decorator, maybe textual explanation in docstring when it is not obvious
- custom 'contract' decorator from  torchio, which wraps the exceptions, see above.
- if you don't like it, you can just disable contracts with a simple call.
  (Redefine the contract function in torchio to a no-op, so they will not be just ignored,
  this could depend on environmental variables, like TORCHIO_DISABLE_CONTRACTS=1, see the dotenv package,
 [https://github.com/theskumar/python-dotenv](https://github.com/theskumar/python-dotenv) )
  
But i am also happy without pycontracts, it was just a soft recommendation. :)
