### ISSUE TITLE
Add support to average overlapping patches in aggregator

### ISSUE THREAD

**Issue by fepegar** [fepegar/torchio#304]
[From the [PyTorch forum](https://discuss.pytorch.org/t/torchio-new-library-for-efficient-3d-data-augmentation-and-patch-based-training/65902/5?u=fepegar)]

@soumickmj said:

> Dear @fepegar, thanks for creating the nice TorchIO library. I have a question regarding the inference part of the Path-based pipeline. If I have understood it correctly, if we set patch overlap, during add batch of grid aggregator, it crops the patch and put it in. Now I wouldn’t like it to be chopped off, rather, the overlap part of the patch to be averaged. Is there already some way to do it with TorchIO?
If not, do you have some tips for doing so? I would write the code by making it compatible with TorchIO and also share the code with you if you would like to integrate it. Thanks.

@fepegar said:

> Hi, @soumickmj. We haven’t implemented this feature yet. I agree it would be useful, so it’d be great if you could contribute with that code!

@soumickmj said:

> Hi @fepegar, Sure. Do you have any tips regarding where it should be implemented?
I will do the implementation and share it with you. I also wrote a wrapper for the Image class, which works with H5 datasets, can also be used for lazy loading of patches. If you want, I can share it with you.

**Comment by fepegar** [comment]
> Do you have any tips regarding where it should be implemented?

I guess it could be a new class in `torchio/data/inference/aggregator.py`. If it's similar to the `GridAggregator`, it could inherit from it. Or the feature could be added as a keyword argument.

> I also wrote a wrapper for the Image class, which works with H5 datasets, can also be used for lazy loading of patches. If you want, I can share it with you.

Awesome! Yes, please.

**Comment by dvolgyes** [comment]
One remark, it would be nice to make this somewhat parametrizable.
E.g. I think in a weighting where the weight is inversely proportional to the distance from the edge of the non-overlapping region.
Of course, the function could be anything, it doesn't have to be 1/d.

A very simple impementation would be summing up the weights in a volume (W), and summing up the values in another (V),
and return the ratio (V/W).

Since the patch size and the overlap is fixed, it is enough to calculate the weighing scheme once, and use this "weight-patch".
In most simple averaging without any positioning, it could be just ```w=torch.ones_like(patch)```.

So four steps  would be needed i guess:
- generate a patch, where the inside region (non-overlapping) gets a 0 distance, and anything in the overlapping region
gets a distance of D (measured from the edge of the non-overlapping part).
- transform the distance into weights. E.g. ```torch.exp(-distance*(lambda/overlap_size))```
or  ```1. / (1+x.)```
- not only add up the values during accumulation, but also the weights (two accumulation arrays)
- return the ``(values / weights)```

This scheme should be able to  handle complex cases (multiple overlapping boxes in the center region, no overlap at the edge, etc.)

**Comment by soumickmj** [comment]
Hey @fepegar, thanks for creating the issue. I will be working on it soon and update you with the code.

Thanks for the suggestion @dvolgyes . I will first finish the non-weighted version and then look into your recommended method.

**Comment by soumickmj** [comment]
I wrote a version without the weighting function. Please have a look @fepegar #307

**Comment by fepegar** [comment]
Closing for now. Feel free to reopen if you're able/willing to contribute with weighted average!
