### ISSUE TITLE
Faster implementation for WeightedSampler

### ISSUE THREAD

**Issue by fepegar** [fepegar/torchio#312]
Discussion about how to make the `WeightedSampler` faster. It stems from a discussion with @dvolgyes and @romainVala in #296.

Related to #308.

@dvolgyes:

> WS calculates CDF every time,
this can be very time (and memory) consuming. This calculation grows linearly with the volume size

The bottleneck seems to be in `np.argsort`:

https://github.com/fepegar/torchio/blob/c3c5e77d2cddfdff03ad00453a76d3f76c360061/torchio/data/sampler/weighted.py#L188

I think a good solution, proposed by @dvolgyes and myself, is downsampling the sampling map for faster computation. The downsampling factor can be passed by the user as a kwarg.

**Comment by dvolgyes** [comment]
Well, as you said, i didn't remove argsort, but actually i wanted.
I struggle to see why is it needed.
I think it is not needed at all.
You do not needd to order probabilities.
Cumsum will make an increasing array (cdf), you take a sample from this with searchsorted,
and convert it back to coordinates with unravel.
Sorting is both expensive and unnecessary.
(And you can even introduce bugs with it, and i have to think, because at this moment i don't see
if the current implementation is correct or not.)
Anyway, so i meant to remove argsort and argmax at the same time, and that would make it quite fast. :)
(Regardless of downsampling.)

**Comment by fepegar** [comment]
The implementation is inherited from NiftyNet's, I understood it at the time and reimplemented it here. It's great that you have noticed that some operations are not needed. I'll check that PR.

**Comment by dvolgyes** [comment]
Not counting probable some style issues, the code should work. 
Check it out if it is a) fast enough, b) works as intended. :)

**Comment by fepegar** [comment]
Improvement on CDF computations added by @dvolgyes on `v0.17.41`. Closing this for now. Will reopen if we want to add the downsampling feature.

@OeslleLucena, lmk if you're interested in working on that!
