### ISSUE TITLE
A new transform that would clip intensities

### ISSUE THREAD

**Issue by sarthakpati** [fepegar/torchio#347]
**🚀 Feature**

An "intensity clipping" transform would be very useful.

**Motivation**

When working with CT images, where the intensities have physical meaning, for example, to pick up liver in abdominal CT, we can simply pick up all intensities between `[-50,200]` and make the rest zero.

**Pitch**

Basing on [RescaleIntensity](https://torchio.readthedocs.io/transforms/preprocessing.html?highlight=RescaleIntensity#torchio.transforms.RescaleIntensity), a **ClipIntensity** transform could be implemented, which takes hard intensity ranges and not percentiles as input.

**Alternatives**

It would be feasible to put this into the training loop directly, but that kind of defeats the purpose.

**Additional context**

N.A.

**Comment by sarthakpati** [comment]
I will use this with Lambda, closing this and the PR.

**Comment by mattwarkentin** [comment]
@fepegar Is there any interest in resurrecting this issue? I still think there is value in having a `torchio` native implementation for clipping instead of having users manually create this with a `torhcio.Lambda` transform. It is a simple enough transform and seems like there is an appetite for this transform among some of the `torhcio` users. Thoughts? Happy to contribute a PR.

**Comment by fepegar** [comment]
> Happy to contribute a PR.

Sounds good, thanks!
