### ISSUE TITLE
AffineTransform landmarks segmentation out of frame

### ISSUE THREAD

**Issue by che85** [fepegar/torchio#355]
I would like to use RandomeAffine transform on the input data of my FCN.

When running affine transform, you always want to make sure that you are applying the same transform to all input images (label, intensity).

I am having the following situation:

Consider one FCN input being a landmark segmentation (tiny blob). After applying the random affine transform, it would end up being somewhere outside the frame. Therefore, all pixel values of the output volume would be 0 and further data augmentation techniques might fail.

If this kind of situation happens, the affine transform (already applied to other input images) should be reverted and a new random transform should be generated applied. This process should be repeated until successfully applied for all. 

Is there a way of doing this with torchio, or do I have to implement this functionality myself (if have done that myself in our local project)?

**Comment by fepegar** [comment]
I'm not sure why you need to revert transforms here. Can't you just discard the transformed images that you don't want? Anyway, I'm working on a PR to invert transforms: #353.

**Comment by romainVala** [comment]
HI, 
I agree with fernado, discard may be the option. because inverting will add some extra interpolation, (and computation time)

personnaly, I do not use translation to avoid losing image part, but with rotation (and scallng) you will also get some missing value in the image border. Note that the 0 can be change playing with `default_pad_value` parameters.

I thing that knowing the volume of missing value, would be an nice feature to add to this transform. May be it may help the selecting process if one which to discard too big missing volume, 
but this volume should be very correlated to the amplitude, of the rotation you use, so may be controlling this amplitude would make the job ...

**Comment by che85** [comment]
I think discard was the right word to use. I wasn't actually going to "revert" the transform. Sorry for the miscommunication.

When doing data augmentation, are you working on the actual data or are you creating temporary copies and overwriting the originals if everything succeeded? 

Locally, I am **applying** the **affine** transform **to** a current **data** (e.g. images, labels, landmark labels) **copy**. If any of the transformed data consists **only of 0 value pixels**, I **throw an error** and **discard** the **current data copy** and **do** it **again** until a random affine is found that transformed the data successfully. The original data will then be updated.

This might not be the most performant method, but at least I am processing the input data in parallel to compensate for it.

**Comment by fepegar** [comment]
I see. I guess this is how I would do it:

```python
while True:
    augmented = transform(data)
    if is_valid(augmented):
        break
```

where `is_valid` is a function that checks that no images in the input are all 0.

I suppose this is a disappointing answer, as this is probably similar to what you're already doing (but more basic as it's not in parallel).

May I ask what type of data you're working with and why your landmarks might disappear after augmentation?
