### ISSUE TITLE
RandomGamma, can warning be ignored?

### ISSUE THREAD

**Issue by dmus** [fepegar/torchio#368]
When training a model with RandomGamma this warning pops up:

> Fractional exponentiation of negative values is generally not
>         well-defined for non-complex numbers.
>         If negative values are found in the input image...

I do not really know what RandomGamma is doing (except for what is in the docs). For which cases is this a useful augmentation? For mri's from different hospitals? Different field strengths or vendors?

And can this warning be ignored or is is better to rescale to positive numbers only?

**Comment by fepegar** [comment]
Have you read [the docs on `RandomGamma`](https://torchio.readthedocs.io/transforms/augmentation.html#randomgamma)? There you can find what the transform does. There is a yellow warning note that explains what the warning message means and there's a link to a Wikipedia article to understand what the transform does and why it's useful.

More info here: https://math.stackexchange.com/questions/317528/how-do-you-compute-negative-numbers-to-fractional-powers

I haven't had the chance to use it for my own experiments yet, but I suspect it's useful (and fast) for all modalities.

I suggest you try it on images with negative and positive values in order to decide whether to ignore the warning or not. I think in general it can be safely ignored.

**Comment by romainVala** [comment]
basically the randomGamma perform a non linear pertubation of the image contrast.
I think it is a good thinks to add since we know the contrast is changing from scanner to scanner
