### ISSUE TITLE
LabelSampler showing none, but Label has nonzero values

### ISSUE THREAD

**Issue by meghbhalerao** [fepegar/torchio#392]
Hi all,
I am facing a strange issue with `LabelSampler`. Here is the code for initialization of `LabelSampler`:
```python
    sampler = torchio.data.LabelSampler(patch_size)
    patches_queue = torchio.Queue(subjects_dataset, max_length=q_max_length,
                                  samples_per_volume=q_samples_per_volume,
                                  sampler=sampler, num_workers=q_num_workers,
                                  shuffle_subjects=False, shuffle_patches=True, verbose=q_verbose)
```
For some images in my dataset, it throws the error: 
```python 
RuntimeError: Empty probability map found: /path/to/mask/
```
But, when I have a look at these images, the mask is **non-zero**, but still this error is thrown. 
I am confused regarding this issue. Here is the link to the zip file for the case which is showing this error: https://drive.google.com/file/d/1kJ7DORGzZt8DXflS3bJz-Hj4gcWmrBe7/view?usp=sharing
Please let me know if something is not clear. 
Thanks for your help!
Megh

**Comment by fepegar** [comment]
Thanks for sharing the data. What's the patch size?

**Comment by meghbhalerao** [comment]
Hi @fepegar, the patch size is `(144,144,80)`

**Comment by fepegar** [comment]
I can reproduce using this code:

```python
import torchio as tio

patch_size = 144, 144, 80
subject = tio.Subject(
    image=tio.ScalarImage('/private/tmp/ISPY1_1058/first.nii.gz'),
    mask=tio.LabelMap('/private/tmp/ISPY1_1058/mask.nii'),
)
sampler = tio.LabelSampler(patch_size)
patch = next(sampler(subject))
```

I'll investigate this. Thanks for reporting!

**Comment by meghbhalerao** [comment]
Thanks a lot! Please let me know what happens!
Megh

**Comment by fepegar** [comment]
This is happening because the probability map (your `mask` image) is cropped with half the patch size, because what is computed is the probability that a voxel is the **center** of the patch.

![Screenshot](https://user-images.githubusercontent.com/12688084/102884531-a830bd80-4449-11eb-87ad-b4846f864234.png)

In the image above, the candidate voxels to be selected are the ones in the area delimited by the four fiducials, and label is not in there.

A possible solution is padding:

```python
pad = tio.Pad(30)
padded = pad(subject)
patch = next(sampler(padded))
```

![Screenshot_1](https://user-images.githubusercontent.com/12688084/102884536-a961ea80-4449-11eb-8981-bbdfa0bf4047.png)

Now, the mask can be the center of a patch. I will improve the error message with a link to this issue and a suggestion to add some padding.

Does that make sense?

**Comment by meghbhalerao** [comment]
Hi @fepegar,
Thanks so much for your detailed explanation, that makes sense!
Thanks again,
Megh

**Comment by fepegar** [comment]
No worries! Thanks again for reporting, it's very helpful.
