### ISSUE TITLE
Support different default interpolation for LabelMaps

### ISSUE THREAD

**Issue by snavalm** [fepegar/torchio#782]
**🚀 Feature**
Allow to change default interpolation for labels

**Motivation**

When using augmentations, labels are interpolated using SITK nearest. Nearest seems to be producing some strange results, with interpolated labels being smaller than expected (I found this when comparing the same transforms applied with Monai vs torchio). I am attaching some images below as examples:

Original resolution
https://drive.google.com/file/d/1LKkT0vUui31eSGwJXiaVd_wsZxAwkmG1/view?usp=sharing

Slicing all dimensions [::2]
https://drive.google.com/file/d/1QbpjvUGF2PMqFa76hhdXKwUJQ262IyU9/view?usp=sharing

nearest (default)
https://drive.google.com/file/d/12Kk7sKs43X2j1DrIlauLSy0Fn9f8LTG6/view?usp=sharing

label-gaussian
https://drive.google.com/file/d/1cjje6pafVEqIk_xyHBzCdfvV5v1ulFum/view?usp=sharing

label_gaussian seems to be producing almost the same results as slicing and 'nearest' in MONAI 

**Pitch**

It would be great if torchio would support some sort of global configuration that would allow switching the default interpolation for labels to label-gaussian or alternatively a second parameter in augmentation

**Alternatives**

- A global configuration that applies automatically to all spatial transforms / augmentations
- A second parameter in relevant augmentations (i.e. image-interpolation='linear', label-interpolation='label-gaussian')

**Additional context**

Happy to provide other examples if needed. Thanks!

**Comment by romainVala** [comment]
Hi
can you describe, or point me on monai doc, to understand what is Slicing and label Gaussian ?

**Comment by snavalm** [comment]
Hi,

Just to clarify, all of the example images that I attached before where downsampling from [192,384,320] to [96,192,160] (half resolution in the 3 dimensions)

By **slicing** I mean doing the downsampling selecting one voxel every 2 in all dimensions (e.g. for a 3d image, get the numpy array and then slicing [:,::2,::2,::2])

**label-gaussian** is the option already available in torchio inherited from sitk (I would like to be able to set this as default)
https://torchio.readthedocs.io/transforms/transforms.html#interpolation

**Comment by romainVala** [comment]
there may be some better way, but a quick one is to declare your labels as `ScalarImage` instead of `LabelMap`

**Comment by snavalm** [comment]
Typically you want to apply transforms to both images and labels. You are correct that I could use ScalarImage and then use image_interpolation = label_gausian, however this would apply label_gaussian interpolation to the images themselves as well which is not right

**Comment by romainVala** [comment]
then you have to compose 2 transforme, with include / exlcude parameters, so that the first one apply to your image and the second one to your label

**Comment by snavalm** [comment]
Thank you for your answer, just to check my understanding, if I apply the suggested solution with random affines, wouldn't I get different transformations for labels and images? I take that you are not interested in the suggested enhancement request so this can be closed. 
For information, the reason why I found this is that I trained the same segmentation network using equivalent monai and torchio augmentation pipelines and models trained on torchio underperformed consistently the ones with monai by slightly more than 3 DICE points. The odd interpolation of labels described here account for most of the difference (about 2 DICE points) but there seems to be something else that I haven't diagnosed yet.

**Comment by romainVala** [comment]
my bad, you are right, it does make sense to separate in 2 transforms...

No need to close, I was just proposing a (bad) alternative, but I do agree we should do it more explicitly. I do think it is an important issue, and we already discuss it previously in  #342)

I did not test the LabelGaussian method (I will !), but i should be close, to the alternative I tested : to use linear interpolation on a 4D onehot encoding and going back to the label (with argmax).
In  #342 I did not found very big difference between the 2 methods, and we did not incorporate it into torchio, but In your case there seems to be a large effect. I think the bad interpolation of nearest is worth when dealing with small region (and large anisotropic voxel resolution), which may explain why you found up to 3 dice point 

So I do agree it make sense to propose something else than only NearestNeighbor for label files
May be a simple (and easy) solution is just to change the interpolation attribute, to 2 separate attributes :
image_interpolation And label_interpolation. (with default value linear and nearest)

It should be an easy PR if you want to give a try, or let see what @fepegar will say ...

**Comment by snavalm** [comment]
Sorry for the delay, I was off during the winter break. I will submit a PR with the changes, I had the changes implemented in a local fork

Thanks

**Comment by romainVala** [comment]
Hi @snavalm , 
do you have time to make a PR ?

I actually also need to test different interpolation for labels, so I was thinking to just add an extra argument label_interpolation (by default to user), to let the user make the choice

tel me if you do not have time, I'll propose one ...

thanks

**Comment by snavalm** [comment]
Hi, sorry, I made the changes but got pulled into something else and never
managed to test them properly. My change was to add a label_interpolation
parameter instead of hardcoded nearest. If you can implement this it would
be great.

**Comment by fepegar** [comment]
Hi, @snavalm. Thanks for reporting this. Could you please share the pair of 3D images?

**Comment by romainVala** [comment]
your are not convince it is necessary ?
if you are interested, I have an other working case, on partial volume maps (label 4D with value between [0 1]) I did the following test : apply a random affine, and the inverse affine to get back in the same space, and then I compare the twice transformed label  with the original label (dice, or L1).
I did this for 3 interpolation nearest linear and spline, and the one that perturbe less the label is bspline 
I compute it for 4 Gray Matter partial volume map (at different spatial resolution 0.7 / 1 / 1.4 / 2.8 mm)

![PV_interpolation_short](https://user-images.githubusercontent.com/5611962/150162288-44268f1d-c3f1-46e2-88d8-cceace3a2215.png)

Actually with the L1 metric, nearest interpolation seems to be better, but I wonder if nearest interpolation is not advantage by the fact I need to do 2 affine.

**Comment by snavalm** [comment]
Hi, thank you for looking into this, I have uploaded example images here:

https://drive.google.com/file/d/1dZr2tLbAYsqWBhPHX3TSX70v9CzMCUMi/view?usp=sharing

I have also managed to do the PR tonight (jupyter notebook in the zip file above uses label_interpolation option) to show the differences in the example images

**Comment by fepegar** [comment]
@romainVala, I wouldn't use nearest neighbor interpolation for the continuous values in the partial-volume maps. Also, B-spline might output values outside [0, 1], which is probably undesired. Isn't linear interpolation working well?

---

![Screenshot](https://user-images.githubusercontent.com/12688084/150405524-b77b8457-e98c-4541-b29f-4f0550ad4789.png)

I know the screenshot is busy, but let me try to explain:
- Green: original resolution
- Red: nearest in TorchIO
- Violet: label Gaussian in TorchIO
- Blue: nearest in Slicer (Resample Scalar Volume module)

In the screenshot, the nearest neighbor interpolation in TorchIO generates results that are further from the original (green). I fear this is because the segmentation has been performed manually along 2D slices, and there is an outlier in the slice that you cherry-picked (75). If I cherry-pick other slices, we get:

![Screenshot_2](https://user-images.githubusercontent.com/12688084/150406238-2132bd47-0390-4175-813e-b034a33ceccc.png)

where we see smaller differences between the approaches.

---

The difference between the Slicer and TorchIO results are probably due to implementation details.

Ideally, we would investigate the source of discrepancy and improve the implementation. Moreover, the label Gaussian is 1) meant to be used for multi-label images and 2) slower (I think), as it applies a Gaussian filter before interpolating.

In practice, though, I suppose we can just add the `label_interpolation` kwarg, if you think it empirically works better for your use case. What do you think? Honestly, I don't really have the time to investigate this issue deeply at the moment.

**Comment by romainVala** [comment]
> @romainVala, I wouldn't use nearest neighbor interpolation for the continuous values in the partial-volume maps. Also, B-spline might output values outside [0, 1], which is probably undesired. Isn't linear interpolation working well?

well, from the graphic I post you can see that linear interpolation is the worst solution, in the sense that it perturbs the most the labels (it is the konwn bluring effect we all know, that comes with interpolation, but here I can give a quantitative evaluation ... on L1 or dice score ...
funny is that B-spline seems the best from the dice score perspective but not from the L1 ... which is quite puzzeling to me as it may not be the best choice either ...

Any way, In practice I need to test different interpolation for my labelmap. Note that even though it is not a binary map, it have to be a Label, so that is why I need this `label_interpolation` kwarg

if you are interested in a visual demonstration of what is measure in the figure, here are a giff animation with the original PV map and this PV map after the 2 interpolation (random affin and its inverse

If I use linear interpolation
![interp_back_linear](https://user-images.githubusercontent.com/5611962/150484800-e5444e87-bea6-4569-b123-b647dac2b899.gif)
)
for nearest interpolation
![interp_back_nearest](https://user-images.githubusercontent.com/5611962/150484891-9e84b902-ac96-4f34-a045-5e28d8bf6c54.gif)

and for bspline
![interp_back_spline](https://user-images.githubusercontent.com/5611962/150484920-ff12aeca-fcc6-4903-98c3-15ea38d78d77.gif)

**Comment by romainVala** [comment]
> The difference between the Slicer and TorchIO results are probably due to implementation details.

that sounds weird to me, how can it be so different ... ? nearest interpolation is quite easy to implement ... no ? (may be one of the 2 method does not take the voxel center ... (but may be the voxel corner ... but would be really a weird choice ...) 


not sure how to investigate since we rely on the sitk implementation ...  (and I do not know Slicer )

But I just look to the interpolation with 2 different software: SPM and mrtrix,  and surprise ...
they are different too ! (note that SPM nearest interpolation (for this example) gives me the exact same roi as torchio ) may be mrtrix implementation would give the exact same as Slicer ...(I would be curious, if you can just share the resample mask by Slicer, (or just compare it with mrtrix interpolation ... mrtransform )

may be an explanation about why we do see so much differences, is because we look at a very special case a factor 2 downsampling. So a "low res" voxel contains exactly 8 "high res" voxel . Now imagine a "low res" voxel which contains 4 "hig res" voxel in the mask and 4 outside the mask , how do you define with nearest if it becomes a voxel mask or not ?
so implementation choice >0.5 or >=0.5 will give different results ...

So may be it is not worth to investigate further: the nearest interpolation can lead to noisy results ... we already know that ... still it is the only choice for a label ... so lets add this `label_interpolation`  kwarg so that one can easily explore what best suite our needs ...
so

**Comment by fepegar** [comment]
Thanks for the GIFs and the explanation, @romainVala. 

> that sounds weird to me, how can it be so different ... ? nearest interpolation is quite easy to implement ... no ? (may be one of the 2 method does not take the voxel center ... (but may be the voxel corner ... but would be really a weird choice ...)
not sure how to investigate since we rely on the sitk implementation ... (and I do not know Slicer )
But I just look to the interpolation with 2 different software: SPM and mrtrix, and surprise ...
they are different too ! (note that SPM nearest interpolation (for this example) gives me the exact same roi as torchio ) may be mrtrix implementation would give the exact same as Slicer ...(I would be curious, if you can just share the resample mask by Slicer, (or just compare it with mrtrix interpolation ... mrtransform )

It's also important to notice that the Slicer module is to change the spacing, like `Resample` in TorchIO (not `Resize`). So yeah I think it does depend on where the origin is set etc.

> may be an explanation about why we do see so much differences, is because we look at a very special case a factor 2 downsampling. So a "low res" voxel contains exactly 8 "high res" voxel . Now imagine a "low res" voxel which contains 4 "hig res" voxel in the mask and 4 outside the mask , how do you define with nearest if it becomes a voxel mask or not ?
so implementation choice >0.5 or >=0.5 will give different results ...

Yes, I do think that this is a special case that might be more noticeable than others.

> So may be it is not worth to investigate further: the nearest interpolation can lead to noisy results ... we already know that ... still it is the only choice for a label ... so lets add this label_interpolation kwarg so that one can easily explore what best suite our needs ...

I agree that this ends up being the right decision.

**Comment by fepegar** [comment]
This is a link to the Slicer scene, in case anyone is curious: https://we.tl/t-SqTPxf5X4O
It will expire in 7 days.

And this is the code for the Resample module in Slicer: https://github.com/Slicer/Slicer/blob/df306df93627a37029b269f9bce33e15806b40a1/Modules/CLI/ResampleScalarVolume/ResampleScalarVolume.cxx#L52
